### ISSUE TITLE
using ECMAScript 6 breaks the component

### ISSUE THREAD

**Issue by ArthurJahn** [salte-io/salte-rating#5]
### Description

The component doesn't work in Safari and Older browsers because of the `let` used in some methods. That is not supported yet.
### Outcome

<img width="500" alt="captura de tela 2016-10-06 as 15 43 46" src="https://cloud.githubusercontent.com/assets/2107018/19165846/c9332516-8bdb-11e6-8434-bd5d53915490.png">
### Steps to reproduce

Run the component in Safari Version 9.1.3 (11601.7.8)
### Browsers Affected
- [ ] Chrome
- [ ] Firefox
- [x] Safari 9
- [x] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by cecilia-sanare** [comment]
Hey @ArthurJahn thanks for taking the time to bring this bug to our attention!

I ended up submitting a pull request (https://github.com/salte-io/salte-rating/pull/7) that should contain a fix for your issue.
